apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vela-server.fullname" . }}
  labels:
    {{- include "vela-server.labels" . | nindent 4 }}
data:
  {{/*
    map all sub-keys of the "env" key to allow greater flexibility
  */}}
{{- range $envKey, $envVal := .Values.env }}
  {{ $envKey | upper }}: {{ $envVal | quote }}
{{- end }}
