apiVersion: apps/v1
kind: Deployment
metadata:
  name: vela-server-deployment
spec:
  selector:
    matchLabels:
      app: vela-server
  replicas: 1
  template:
    metadata:
      labels:
        app: vela-server
    spec:
      containers:
      - name: vela-server
        image: target/vela-server:v0.14.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: {{ include "vela-server.fullname" . }}