apiVersion: v1
kind: Service
metadata:
  name: {{ include "vela-server.fullname" . }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    {{- include "vela-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ if kindIs "string" .Values.service.port }}{{ tpl .Values.service.port $ }}{{ else }}{{ .Values.service.port }}{{ end }}
      targetPort: {{ if kindIs "string" .Values.env.VELA_PORT }}{{ tpl .Values.env.VELA_PORT $ }}{{ else }}{{ .Values.env.VELA_PORT }}{{ end }}
      protocol: TCP
      name: http
  selector:
    {{- include "vela-server.selectorLabels" . | nindent 4 }}
