apiVersion: v1
kind: ServiceAccount
metadata:
  # name: {{ include "vela-worker.fullname" . }}
  name: vela-worker
  # labels:
  #   {{- include "vela-worker.labels" . | nindent 4 }}
  # {{- if .Values.serviceAccount.annotations }}
  # annotations:
  #   {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  # {{- end }}
  # {{- if .Values.serviceAccount.pullSecret }}
# imagePullSecrets:
# - name: "{{ .Values.serviceAccount.pullSecret }}"
#   {{- end }}

# {{/* A Role is created for every namespace we want to run builds in. */}}
# {{- $root := . }}
# {{- range .Values.rbac.buildNamespaces }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # name: {{ include "vela-worker.fullname" $root }}
  name: vela-worker
  namespace: default
  # labels:
  #   {{- include "vela-worker.labels" $root | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      # github.com/go-vela/pkg-runtime/runtime/kubernetes/client.go
      - get     # client.TailContainer
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      # github.com/go-vela/pkg-runtime/runtime/kubernetes/client.go
      - create  # client.RunContainer
      - patch   # client.RunContainer
      - get     # client.InspectContainer
                # ! client.InspectImage (only logs a noop 'kubectl get pod' command)
                # ! client.InspectVolume (only logs a noop 'kubectl get pod' command)
                # ! client.InspectNetwork (only logs a noop 'kubectl get pod' command)
      - list    # client.TailContainer
      - update
      - watch   # client.WaitContainer
      - delete  # client.DeleteContainer
# {{ end -}}

# {{/* The role gets bound to the runner's ServiceAccount in the runner's namespace. */}}
# {{- range $nsName := .Values.rbac.buildNamespaces }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # name: {{ include "vela-worker.fullname" $root }}
  name: vela-worker
  namespace: default
  # labels:
  #   {{- include "vela-worker.labels" $root | nindent 4 }}
subjects:
  - kind: ServiceAccount
    # name: {{ include "vela-worker.fullname" $root }}
    name: vela-worker
    namespace: default
roleRef:
  kind: Role
  name: vela-worker
  # name: {{ include "vela-worker.fullname" $root }}
  apiGroup: rbac.authorization.k8s.io
# {{ end -}}