apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../../go-vela/worker/docker-compose.yml -o ./worker/
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../../go-vela/worker/docker-compose.yml -o ./worker/
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/vela: "true"
        io.kompose.service: worker
    spec:
      serviceAccountName: vela-worker
      containers:
        - env:
            - name: EXECUTOR_DRIVER
              valueFrom:
                configMapKeyRef:
                  key: EXECUTOR_DRIVER
                  name: env
            - name: QUEUE_DRIVER
              valueFrom:
                configMapKeyRef:
                  key: QUEUE_DRIVER
                  name: env
            - name: QUEUE_ADDR
              valueFrom:
                configMapKeyRef:
                  key: QUEUE_ADDR
                  name: env
            - name: VELA_BUILD_LIMIT
              valueFrom:
                configMapKeyRef:
                  key: VELA_BUILD_LIMIT
                  name: env
            - name: VELA_BUILD_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: VELA_BUILD_TIMEOUT
                  name: env
            - name: VELA_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: VELA_LOG_LEVEL
                  name: env
            - name: VELA_RUNTIME_DRIVER
              valueFrom:
                configMapKeyRef:
                  key: VELA_RUNTIME_DRIVER
                  name: env
            - name: VELA_RUNTIME_PRIVILEGED_IMAGES
              valueFrom:
                configMapKeyRef:
                  key: VELA_RUNTIME_PRIVILEGED_IMAGES
                  name: env
            - name: VELA_EXECUTOR_ENFORCE_TRUSTED_REPOS
              valueFrom:
                configMapKeyRef:
                  key: VELA_EXECUTOR_ENFORCE_TRUSTED_REPOS
                  name: env
            - name: VELA_SERVER_ADDR
              valueFrom:
                configMapKeyRef:
                  key: VELA_SERVER_ADDR
                  name: env
            - name: VELA_SERVER_SECRET
              valueFrom:
                configMapKeyRef:
                  key: VELA_SERVER_SECRET
                  name: env
            - name: WORKER_ADDR
              valueFrom:
                configMapKeyRef:
                  key: WORKER_ADDR
                  name: env
            - name: WORKER_CHECK_IN
              valueFrom:
                configMapKeyRef:
                  key: WORKER_CHECK_IN
                  name: env
            # k8s specific
            - name: VELA_RUNTIME_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  key: VELA_RUNTIME_NAMESPACE
                  name: env
            - name: VELA_K8S_PAUSE_IMAGE
              valueFrom:
              configMapKeyRef:
                key: VELA_K8S_PAUSE_IMAGE
                name: env
          # this image MUST support using a custom VELA_K8S_PAUSE_IMAGE
          # for M1 specifically, use VELA_K8S_PAUSE_IMAGE: registry.k8s.io/pause:3.6
          image: target/vela-worker:latest
          name: worker
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
      volumes:
        - name: worker-claim0
          persistentVolumeClaim:
            claimName: worker-claim0
status: {}
