{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- if .Values.serviceAccount.pullSecret }}
  imagePullSecrets:
  - name: "{{ .Values.serviceAccount.pullSecret }}"
  {{- end }}
{{- end }}
